# Generated by Django 4.0.2 on 2022-05-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapps', '0002_price_coin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
